export const UPDATE_RUN_NUM_BOOL = 'UPDATE_RUN_NUM_BOOL';
export const UPDATE_GLOBAL_BRAND = 'UPDATE_GLOBAL_BRAND';
export const UPDATE_NAV_MENU_LIST = 'UPDATE_NAV_MENU_LIST';
export const UPDATE_WEBSOCKET_DATA = 'UPDATE_WEBSOCKET_DATA';
export const UPDATE_WEBSOCKET_DATA_MAP = 'UPDATE_WEBSOCKET_DATA_MAP';
export const CLEAR_WS_TASK = 'CLEAR_WS_TASK';
